### ISSUE TITLE
Video scrolly loading slowly on desktop Firefox

### ISSUE THREAD

**Issue by rhandleymcc** [mcclatchy/security-for-sale#10]
Video scrolly loading slowly on desktop Firefox

**Comment by rhandleymcc** [comment]
https://user-images.githubusercontent.com/101584475/165396790-60495cd8-c4a7-4057-9866-8383cd58612f.mov

**Comment by dmnewcomb** [comment]
I did a few things to improve performance here:

- Changed the Svelte reactive throttle back to 33 milliseconds
- Ran the original `mp4` through an intermediate `ffmpeg` processing step that creates a `webm`
    - `ffmpeg  -i <input>.mp4  -b:v 0  -crf 30  -pass 2  <output>.webm`
- Ran the `webm` through Handbrake using `keyint=2` instead of `keyint=30`
    - 30 is OK for mobile, 3 was working for Safari and Chrome, 2 seemed best for Firefox

**Comment by dmnewcomb** [comment]
Closed by https://github.com/mcclatchy/security-for-sale/commit/1042580a682a25f64f87cff4f414d036fcda79b5
