### ISSUE TITLE
First phrase in Trailer graphic overlaps image on safari iPad 10.5

### ISSUE THREAD

**Issue by rhandleymcc** [mcclatchy/security-for-sale#5]
First phrase in Trailer graphic overlaps image on safari iPad 10.5 in

**Comment by rhandleymcc** [comment]
![Image from iOS](https://user-images.githubusercontent.com/101584475/165186460-2653d947-e367-471e-9a6b-b3bb03f41501.png)

**Comment by dmnewcomb** [comment]
Fixed by making a separate `ipad` aspect ratio in the AML for scrolling videos. Need to figure out a cleaner solution that tracks specific spots on a video.
