### ISSUE TITLE
"scroll to continue" appears in the middle of lead image on iPhone 7

### ISSUE THREAD

**Issue by rhandleymcc** [mcclatchy/security-for-sale#6]
"scroll to continue" appears in the middle of lead image on iPhone 7

**Comment by rhandleymcc** [comment]
![Image from iOS](https://user-images.githubusercontent.com/101584475/165190372-112e772a-f784-4a7c-8bbb-1b6dff7e4759.png)

**Comment by dmnewcomb** [comment]
Fixed this bug across many iPhone formats. It turns out this bug was occurring on iPhone 7-**plus**, not iPhone 7 and those have different aspect ratios and resolutions
