### ISSUE TITLE
Timeline Map text overlaps image when scrolling

### ISSUE THREAD

**Issue by rhandleymcc** [mcclatchy/security-for-sale#7]
Timeline Map text overlaps image when scrolling.

**Comment by rhandleymcc** [comment]
https://user-images.githubusercontent.com/101584475/165335321-565204f7-c3a5-4e15-a34a-8e1078bb131e.MP4

**Comment by dmnewcomb** [comment]
I changed the text from being `position: fixed` in the Scroller foreground to use `position: absolute` within the Scroller background element. This means the element is absolutely positioned using the `bottom` CSS property right now. This could be troublesome on different iPhones. We'll see
